In [584]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [585]:
import pandas as pd

In [586]:
data = {
    "customer_id": [101, 102, 103, 104],
    "amount": [5000, 20000, 1500, 70000],
    "currency": ["NGN", "NGN", "USD", "NGN"],
    "risk_score": [2, 8, 1, 9]
}

df = pd.DataFrame(data)

print(df)

   customer_id  amount currency  risk_score
0          101    5000      NGN           2
1          102   20000      NGN           8
2          103    1500      USD           1
3          104   70000      NGN           9

In [587]:
print(df.head() )    # first rows
print(df.tail())     # last rows
print(df.shape)       # (rows, columns)
print(df.columns)    # column names
print(df.info())      # data types
print(df.describe())  # statistics

   customer_id  amount currency  risk_score
0          101    5000      NGN           2
1          102   20000      NGN           8
2          103    1500      USD           1
3          104   70000      NGN           9
   customer_id  amount currency  risk_score
0          101    5000      NGN           2
1          102   20000      NGN           8
2          103    1500      USD           1
3          104   70000      NGN           9
(4, 4)
Index(['customer_id', 'amount', 'currency', 'risk_score'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  4 non-null      int64
 1   amount       4 non-null      int64
 2   currency     4 non-null      object
 3   risk_score   4 non-null      int64
dtypes: int64(3), object(1)
memory usage: 260.0+ bytes
None
       customer_id        amount  risk_score
count     4.000000      4.000000    4.000000
mean    102.500000  24125.000000    5.000000
std       1.290994  31618.494061    4.082483
min     101.000000   1500.000000    1.000000
25%     101.750000   4125.000000    1.750000
50%     102.500000  12500.000000    5.000000
75%     103.250000  32500.000000    8.250000
max     104.000000  70000.000000    9.000000

In [588]:
df[["amount"]]

   amount
0    5000
1   20000
2    1500
3   70000

In [589]:
df[["amount", "risk_score"]]

   amount  risk_score
0    5000           2
1   20000           8
2    1500           1
3   70000           9

**selecting multiple column**

In [590]:
df[df["risk_score"] > 7]

   customer_id  amount currency  risk_score
1          102   20000      NGN           8
3          104   70000      NGN           9

In [591]:
df[df["amount"] > 10000]

   customer_id  amount currency  risk_score
1          102   20000      NGN           8
3          104   70000      NGN           9

In [592]:
df["large_flag"] = df["amount"] > 10000
df

   customer_id  amount currency  risk_score  large_flag
0          101    5000      NGN           2       False
1          102   20000      NGN           8        True
2          103    1500      USD           1       False
3          104   70000      NGN           9        True

In [593]:
df["risk_category"] = df["risk_score"].apply(
    lambda x: "High" if x > 7 else "Low")
df

   customer_id  amount currency  risk_score  large_flag risk_category
0          101    5000      NGN           2       False           Low
1          102   20000      NGN           8        True          High
2          103    1500      USD           1       False           Low
3          104   70000      NGN           9        True          High

In [594]:
df.groupby("currency")["amount"].sum()

currency
NGN    95000
USD     1500
Name: amount, dtype: int64

In [595]:
df.groupby("currency")["risk_score"].mean()

currency
NGN    6.333333
USD    1.000000
Name: risk_score, dtype: float64

In [596]:
df.sort_values("amount", ascending=False)

   customer_id  amount currency  risk_score  large_flag risk_category
3          104   70000      NGN           9        True          High
1          102   20000      NGN           8        True          High
0          101    5000      NGN           2       False           Low
2          103    1500      USD           1       False           Low

In [597]:
df.isnull().sum()

df.fillna(0)

df.dropna()

   customer_id  amount currency  risk_score  large_flag risk_category
0          101    5000      NGN           2       False           Low
1          102   20000      NGN           8        True          High
2          103    1500      USD           1       False           Low
3          104   70000      NGN           9        True          High

In [598]:
df["risk_category"] = np.where(df["risk_score"] > 7, "High", "Low")
df

   customer_id  amount currency  risk_score  large_flag risk_category
0          101    5000      NGN           2       False           Low
1          102   20000      NGN           8        True          High
2          103    1500      USD           1       False           Low
3          104   70000      NGN           9        True          High

**Using Numpy**

In [599]:
High_value_df = df[df["risk_category"] == "High"]
total_high_df = High_value_df["amount"].sum()
print(total_high_df)

90000

In [600]:
df.groupby("risk_category")["amount"].sum()

risk_category
High    90000
Low      6500
Name: amount, dtype: int64

In [601]:
df.groupby("currency")["risk_score"].mean()

currency
NGN    6.333333
USD    1.000000
Name: risk_score, dtype: float64

In [602]:
df.sort_values("risk_score", ascending=True)

   customer_id  amount currency  risk_score  large_flag risk_category
2          103    1500      USD           1       False           Low
0          101    5000      NGN           2       False           Low
1          102   20000      NGN           8        True          High
3          104   70000      NGN           9        True          High

In [603]:
df.isnull().sum()

df.fillna(0)

df.dropna()

   customer_id  amount currency  risk_score  large_flag risk_category
0          101    5000      NGN           2       False           Low
1          102   20000      NGN           8        True          High
2          103    1500      USD           1       False           Low
3          104   70000      NGN           9        True          High

In [604]:
fraud_df = df[
(df["amount"] > 10000) &
(df["risk_score"] > 7)
]
fraud_df

   customer_id  amount currency  risk_score  large_flag risk_category
1          102   20000      NGN           8        True          High
3          104   70000      NGN           9        True          High

In [605]:
# 1. Define the current exchange rate
usd_to_ngn = 1360.04 

# 2. Create a new 'amount_ngn' column
df["amount_ngn"] = df.apply(
    lambda row: row["amount"] * usd_to_ngn if row["currency"] == "USD" else row["amount"], 
    axis=1
)

# 3. Now you can sum accurately
total_portfolio_value = df["amount_ngn"].sum()
print(f"Total Value in NGN: {total_portfolio_value:,.2f}")

Total Value in NGN: 2,135,060.00

In [606]:
data = {
    "customer_id": [1,2,3,4,5],
    "amount": [1000, 20000, 5000, 70000, 15000],
    "currency": ["NGN", "USD", "NGN", "USD", "NGN"],
    "risk_score": [5, 2, 9, 11, 5]
}

df = pd.DataFrame(data)
df

   customer_id  amount currency  risk_score
0            1    1000      NGN           5
1            2   20000      USD           2
2            3    5000      NGN           9
3            4   70000      USD          11
4            5   15000      NGN           5

In [607]:
df.describe()

       customer_id        amount  risk_score
count     5.000000      5.000000    5.000000
mean      3.000000  22200.000000    6.400000
std       1.581139  27779.488836    3.577709
min       1.000000   1000.000000    2.000000
25%       2.000000   5000.000000    5.000000
50%       3.000000  15000.000000    5.000000
75%       4.000000  20000.000000    9.000000
max       5.000000  70000.000000   11.000000

In [608]:
df["amount"].mean()

np.float64(22200.0)

In [609]:
df[df["amount"] > 10000]

   customer_id  amount currency  risk_score
1            2   20000      USD           2
3            4   70000      USD          11
4            5   15000      NGN           5

**filter customers with amount > 10000**

In [610]:
df["fee"] = df["amount"] * 0.05
df

   customer_id  amount currency  risk_score     fee
0            1    1000      NGN           5    50.0
1            2   20000      USD           2  1000.0
2            3    5000      NGN           9   250.0
3            4   70000      USD          11  3500.0
4            5   15000      NGN           5   750.0

In [611]:
df.sort_values("amount", ascending=False)

   customer_id  amount currency  risk_score     fee
3            4   70000      USD          11  3500.0
1            2   20000      USD           2  1000.0
4            5   15000      NGN           5   750.0
2            3    5000      NGN           9   250.0
0            1    1000      NGN           5    50.0

In [612]:
df.groupby("currency")["amount"].agg(["sum", "mean"])

            sum     mean
currency
NGN       21000   7000.0
USD       90000  45000.0

In [613]:
df["risk_category"] = pd.cut(
    df["risk_score"],
    bins=[0,3,7,10,15],
    labels=["Low","Medium","High", "Overated"]
)
df

   customer_id  amount currency  risk_score     fee risk_category
0            1    1000      NGN           5    50.0        Medium
1            2   20000      USD           2  1000.0           Low
2            3    5000      NGN           9   250.0          High
3            4   70000      USD          11  3500.0      Overated
4            5   15000      NGN           5   750.0        Medium

In [614]:
df["risk_category"].value_counts()

risk_category
Medium      2
Low         1
High        1
Overated    1
Name: count, dtype: int64

In [615]:
import numpy as np

np.random.seed(42)

df = pd.DataFrame({
    "amount": np.random.randint(1000, 100000, 1000),
    "risk_score": np.random.randint(1, 11, 1000)
})

total_volume = df["amount"].sum()
mean_transaction = df["amount"].mean()
high_transactions = (df["amount"] > 50000).sum()
percent_high_risk = (df["risk_score"] > 7).mean() * 100

print(total_volume)
print(mean_transaction)
print(high_transactions)
print(percent_high_risk)

49990156
49990.156
507
29.9

In [616]:
import pandas as pd

transactions = pd.DataFrame({
    "customer_id": [1,2,3,1,2],
    "amount": [5000, 20000, 7000, 15000, 3000]
})

customer = pd.DataFrame({
    "customer_id": [1,2,3],
    "risk_score": [2, 8, 5]
})

In [617]:
df = pd.merge(transactions, customer, on="customer_id", how="left")
df

   customer_id  amount  risk_score
0            1    5000           2
1            2   20000           8
2            3    7000           5
3            1   15000           2
4            2    3000           8

In [618]:
import numpy as np

dates = pd.date_range(start="2024-01-01", periods=5)

df = pd.DataFrame({
    "date": dates,
    "returns": np.random.normal(0.001, 0.02, 5)
})

df.set_index("date", inplace=True)

print(df)

             returns
date
2024-01-01  0.023111
2024-01-02  0.024741
2024-01-03  0.013775
2024-01-04 -0.021860
2024-01-05  0.033669

inplace=True tells the code not to create a new column index

In [619]:
df["rolling_mean"] = df["returns"].rolling(window=3).mean()
df

             returns  rolling_mean
date
2024-01-01  0.023111           NaN
2024-01-02  0.024741           NaN
2024-01-03  0.013775      0.020542
2024-01-04 -0.021860      0.005552
2024-01-05  0.033669      0.008528

calculates the value of 3day rolling window.
0 and 1 is NaN because it needs a 3day return value to cal the mean

In [620]:
slice_to = df["2024-01-02": "2024-01-04"]
slice_to

             returns  rolling_mean
date
2024-01-02  0.024741           NaN
2024-01-03  0.013775      0.020542
2024-01-04 -0.021860      0.005552

In [621]:
df["yesterdate"] = df["returns"].shift(1)
df

             returns  rolling_mean  yesterdate
date
2024-01-01  0.023111           NaN         NaN
2024-01-02  0.024741           NaN    0.023111
2024-01-03  0.013775      0.020542    0.024741
2024-01-04 -0.021860      0.005552    0.013775
2024-01-05  0.033669      0.008528   -0.021860

It shifts yesterday value to today. this is good for predicting model.this tells the computer to look at what happened yesterday to predict what might happen today.

In [622]:
daily_returns = df["returns"] - df["yesterdate"]
print(daily_returns)

date
2024-01-01         NaN
2024-01-02    0.001630
2024-01-03   -0.010966
2024-01-04   -0.035635
2024-01-05    0.055529
dtype: float64

In [623]:
weekly_returns = df["returns"].resample("W").mean()
print(weekly_returns)

date
2024-01-07    0.014687
Freq: W-SUN, Name: returns, dtype: float64

**Time Series**

In [624]:
df["rolling_mean"] = df["returns"].rolling(window=3, min_periods=1).mean()
df

             returns  rolling_mean  yesterdate
date
2024-01-01  0.023111      0.023111         NaN
2024-01-02  0.024741      0.023926    0.023111
2024-01-03  0.013775      0.020542    0.024741
2024-01-04 -0.021860      0.005552    0.013775
2024-01-05  0.033669      0.008528   -0.021860

day1 give you day1 value while day2 give average of day1 and 2 and so on.

By adding min_periods=1, you are telling Pandas: "Don't wait for a full 3-day window; give me whatever average you can calculate starting from Day 1."

In [625]:
df["rolling_vol"] = df["returns"].rolling(3).std()
df

             returns  rolling_mean  yesterdate  rolling_vol
date
2024-01-01  0.023111      0.023111         NaN          NaN
2024-01-02  0.024741      0.023926    0.023111          NaN
2024-01-03  0.013775      0.020542    0.024741     0.005917
2024-01-04 -0.021860      0.005552    0.013775     0.024364
2024-01-05  0.033669      0.008528   -0.021860     0.028134

This code calculates a 3-Day Rolling Volatility. While the rolling mean tells you the trend, the rolling Standard Deviation (std) tells you how much the "heartbeat" of the market is speeding up or slowing down.

In [626]:
df["expanding_val"] = df["returns"].expanding().mean()
df

             returns  rolling_mean  yesterdate  rolling_vol  expanding_val
date
2024-01-01  0.023111      0.023111         NaN          NaN       0.023111
2024-01-02  0.024741      0.023926    0.023111          NaN       0.023926
2024-01-03  0.013775      0.020542    0.024741     0.005917       0.020542
2024-01-04 -0.021860      0.005552    0.013775     0.024364       0.009941
2024-01-05  0.033669      0.008528   -0.021860     0.028134       0.014687

this cal the average val of everyday except day1

In [627]:
df = pd.DataFrame({
    "currency": ["NGN","NGN","USD","USD"],
    "risk_category": ["Low","High","Low","High"],
    "amount": [5000,20000,40000,3000]
})

pivot = pd.pivot_table(
    df,
    values="amount",
    index="currency",
    columns="risk_category",
    aggfunc="sum",
    margins=True
)

print(pivot)

risk_category   High    Low    All
currency
NGN            20000   5000  25000
USD             3000  40000  43000
All            23000  45000  68000

This is used for quick summary

In [628]:
df = pd.DataFrame({
    "date": pd.date_range("2026-03-1", periods=30),
    "amount": np.random.randint(1000,10000,30)
})
df.set_index("date", inplace=True)
monthly = df.resample("ME").sum()
monthly

            amount
date
2026-03-31  155866

this is total of a monthly revenue

In [629]:
transaction = pd.DataFrame({
    "customer_id": [1,2,9,5,7],
    "amount": [2000,3000,50000,3500,70000]
})
customer = pd.DataFrame({
    "customer_id": [1,5,2,9,7],
    "risk_score": [4,2,5,8,3]
})

df = pd.merge(customer, transaction, on="customer_id", how="left")
df

   customer_id  risk_score  amount
0            1           4    2000
1            5           2    3500
2            2           5    3000
3            9           8   50000
4            7           3   70000

In [630]:
df = pd.DataFrame({
    "returns": np.random.normal(0.001, 0.02, 10)
})
df["rolling_mean"] = df["returns"].rolling(3).mean()
df

    returns  rolling_mean
0 -0.021927           NaN
1 -0.024560           NaN
2 -0.031875     -0.026121
3 -0.016703     -0.024380
4  0.032051     -0.005509
5 -0.030055     -0.004902
6 -0.005071     -0.001025
7 -0.024863     -0.019996
8 -0.011019     -0.013651
9  0.004394     -0.010496

In [631]:
df["cumulative_return"] = (1 + df["returns"]).cumprod() -1
df

    returns  rolling_mean  cumulative_return
0 -0.021927           NaN          -0.021927
1 -0.024560           NaN          -0.045949
2 -0.031875     -0.026121          -0.076359
3 -0.016703     -0.024380          -0.091787
4  0.032051     -0.005509          -0.062677
5 -0.030055     -0.004902          -0.090848
6 -0.005071     -0.001025          -0.095458
7 -0.024863     -0.019996          -0.117948
8 -0.011019     -0.013651          -0.127668
9  0.004394     -0.010496          -0.123835

This answers the question "if I invest x amount today, what will I gain at the end"

In [632]:
df = pd.DataFrame({
    "dates": pd.date_range("2026-03-1", periods=30),
    "amounts": np.random.randint(10,1000,30)
})
df.set_index("dates", inplace=True)
Weekly = df.resample("W").sum()
Weekly

            amounts
dates
2026-03-01      631
2026-03-08     4648
2026-03-15     4458
2026-03-22     1845
2026-03-29     4191
2026-04-05      335

In [633]:
np.random.seed(42)

df = pd.DataFrame({
    "date": pd.date_range("2024-01-01", periods=10000, freq="h"),
    "amount": np.random.randint(1000,100000,10000),
    "currency": np.random.choice(["NGN","USD","EUR"],10000),
    "risk_score": np.random.randint(1,11,10000)
})

df.set_index("date", inplace=True)

monthly_volume = df.resample("ME")["amount"].sum()

monthly_high_risk = df.resample("ME")["risk_score"].apply(
    lambda x: (x > 7).mean()
)

top_risk_months = monthly_high_risk.sort_values(ascending=False).head(3)

print(monthly_volume)
print(monthly_high_risk)
print(top_risk_months)

date
2024-01-31    38123163
2024-02-29    33394661
2024-03-31    37403178
2024-04-30    36911928
2024-05-31    36710862
2024-06-30    35639570
2024-07-31    37006142
2024-08-31    37943214
2024-09-30    36086832
2024-10-31    37125780
2024-11-30    35726201
2024-12-31    38401363
2025-01-31    36783582
2025-02-28    23650399
Freq: ME, Name: amount, dtype: int64
date
2024-01-31    0.315860
2024-02-29    0.310345
2024-03-31    0.284946
2024-04-30    0.320833
2024-05-31    0.310484
2024-06-30    0.295833
2024-07-31    0.268817
2024-08-31    0.309140
2024-09-30    0.287500
2024-10-31    0.248656
2024-11-30    0.297222
2024-12-31    0.282258
2025-01-31    0.295699
2025-02-28    0.324153
Freq: ME, Name: risk_score, dtype: float64
date
2025-02-28    0.324153
2024-04-30    0.320833
2024-01-31    0.315860
Name: risk_score, dtype: float64

This code creates a massive Transaction Monitoring System that analyzes over a year of hourly data to find the most dangerous months for a business.
Line-by-Line Explanation
1. pd.date_range(..., freq="H")
What it does: Generates 10,000 consecutive hours (about 13.8 months) of timestamps.
Real-Life Example: This mimics a Global Digital Bank. Unlike a local shop that opens 9-to-5, a digital bank processes payments 24/7, every single hour.
2. monthly_volume = df.resample("M")["amount"].sum()
What it does: Groups the 10,000 hours into months and adds up all the transaction amounts.
Real-Life Example: The Revenue Report. This tells the CEO how much total cash moved through the platform in January vs. February.
3. monthly_high_risk = df.resample("M")["risk_score"].apply(lambda x: (x > 7).mean())
What it does: For each month, it calculates what percentage of transactions had a risk score of 8, 9, or 10.
Real-Life Example: The Fraud Trend Tracker. It doesn't look at the money; it looks at the behavior. It tells you, "In March, 30% of our traffic looked suspicious."
4. top_risk_months = monthly_high_risk.sort_values(ascending=False).head(3)
What it does: Sorts the months from highest risk to lowest and picks the top 3 "worst" months.
Real-Life Example: The Incident Audit. If a bank gets attacked by hackers, the compliance team uses this to identify exactly which months had the highest density of red flags so they can investigate those specific time periods.

In [634]:
import pandas as pd
import numpy as np

np.random.seed(42)

n = 5000

df = pd.DataFrame({
    "transaction_id": range(1, n+1),
    "customer_id": np.random.randint(1000, 1100, n),
    "date": pd.date_range("2024-01-01", periods=n, freq="h"),
    "amount": np.random.randint(1000, 200000, n),
    "currency": np.random.choice(["NGN","USD","EUR"], n),
    "risk_score": np.random.randint(1, 11, n)
})

df["is_fraud"] = (
    (df["amount"] > 150000) &
    (df["risk_score"] > 8)
).astype(int)
df

,transaction_id,customer_id,date,amount,currency,risk_score,is_fraud
0,1,1051,2024-01-01 00:00:00,24408,EUR,2,0
1,2,1092,2024-01-01 01:00:00,125116,NGN,8,0
2,3,1014,2024-01-01 02:00:00,132208,EUR,7,0
3,4,1071,2024-01-01 03:00:00,18413,EUR,1,0
4,5,1060,2024-01-01 04:00:00,114650,USD,5,0
...,...,...,...,...,...,...,...
4995,4996,1048,2024-07-27 03:00:00,78475,EUR,6,0
4996,4997,1057,2024-07-27 04:00:00,159484,USD,2,0
4997,4998,1038,2024-07-27 05:00:00,83212,USD,2,0
4998,4999,1079,2024-07-27 06:00:00,76379,NGN,2,0
4999,5000,1096,2024-07-27 07:00:00,46591,NGN,3,0

This code builds a Fraud Detection Filter. It’s the logic used by banks to decide which transactions should be instantly blocked or flagged for manual review.
Line-by-Line Explanation
1. n = 5000
What it does: Sets the scale to 5,000 transactions.
Real-Life Example: This is a "mid-sized" batch for a fintech—roughly what a busy payment gateway processes in an hour.
2. df = pd.DataFrame({...})
What it does: Creates a detailed ledger including Who (customer_id), When (date), How much (amount), and How safe (risk_score).
Real-Life Example: This is the Core Banking Ledger. It captures every detail needed for an audit trail.
3. df["is_fraud"] = ((df["amount"] > 150000) & (df["risk_score"] > 8)).astype(int)
What it does: This is the "Decision Engine." It looks for two specific red flags happening at once:
The amount is very high (> ₦150k).
The risk score is critical (9 or 10).
.astype(int): Converts True/False into 1 (Fraud) and 0 (Safe).
Real-Life Example: This is a Hard Rule. Imagine a security guard who only stops people if they are carrying a heavy bag and acting nervous. If only one is true, they pass; if both are true, they are stopped.

In [635]:
df.head()
df.info()
df.describe()
df["is_fraud"].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  5000 non-null   int64
 1   customer_id     5000 non-null   int64
 2   date            5000 non-null   datetime64[ns]
 3   amount          5000 non-null   int64
 4   currency        5000 non-null   object
 5   risk_score      5000 non-null   int64
 6   is_fraud        5000 non-null   int64
dtypes: datetime64[ns](1), int64(5), object(1)
memory usage: 273.6+ KB

is_fraud
0    4793
1     207
Name: count, dtype: int64

> This code is your "Pre-Flight Check." In a fintech audit, you run these commands to ensure your fraud detection rules actually worked and to see how many "criminals" you caught.
Line-by-Line Explanation
1. df.head()
What it does: Shows the first 5 rows of your data.
Real-Life Example: You're taking a quick look at the top of the pile of receipts to make sure the columns like is_fraud and amount actually exist and look correct.
2. df.info()
What it does: Checks for missing data and identifies data types.
Real-Life Example: You're checking the Health of the File. If the date column is listed as "object" (text) instead of "datetime," your time-based fraud filters might fail.
3. df.describe()
What it does: Gives you the "Stats." You see the average transaction amount, the minimum, and the maximum.
Real-Life Example: You look at the Maximum Amount. If your fraud rule is for ₦150k but the max transaction is ₦200M, you realize your rule might be too small and you're missing the "big fish."
4. df["is_fraud"].value_counts()
What it does: Counts how many 0s (Safe) and 1s (Fraud) are in your list.
Real-Life Example: The Daily Scorecard. It tells you exactly how many transactions were flagged.
If you see 4,950 zeros and 50 ones, your system is blocking 1% of traffic.
If you see 0 ones, your fraud rule is too strict and isn't catching anything!

In [636]:
fraud_rate = df["is_fraud"].mean()
print(fraud_rate)

0.0414

In [637]:
df.groupby("currency")["is_fraud"].mean()

currency
EUR    0.038603
NGN    0.037292
USD    0.048615
Name: is_fraud, dtype: float64

This tells you:

“What percentage of each currency is fraudulent?”

If one currency is 10x higher → red flag.

In [650]:
df["amount_band"] = pd.cut(
    df["amount"],
    bins=[0,50000,100000,150000,200000],
    labels=["Low","Medium","High","Very High"]
)
df.groupby("amount_band")["is_fraud"].mean()

/tmp/ipykernel_55/910624077.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("amount_band")["is_fraud"].mean()

amount_band
Low          0.000000
Medium       0.000000
High         0.000000
Very High    0.168019
Name: is_fraud, dtype: float64

This code performs Risk Segmentation. It groups your transactions into buckets based on their size and then calculates the "danger level" for each bucket.
Line-by-Line Explanation
1. pd.cut(df["amount"], bins=[...], labels=[...])
What it does: It takes the continuous numbers in the "amount" column and categorises them into four discrete folders:
₦0 – ₦50k 
 Low
₦50k – ₦100k 
 Medium
₦100k – ₦150k 
 High
₦150k – ₦200k 
 Very High
Real-Life Example: Think of a Bank's Withdrawal Limit. Instead of looking at every specific Naira, the bank treats you differently if you withdraw ₦10k (no ID needed) versus ₦180k (requires extra verification).
2. df.groupby("amount_band")["is_fraud"].mean()
What it does: It looks at each folder (Low, Medium, High, Very High) and calculates the percentage of transactions inside that folder that were marked as is_fraud.
Real-Life Example: You are asking the computer: "In which of these four folders are the criminals hiding?"

In [639]:
customer_risk = df.groupby("customer_id").agg({
    "amount": "mean",
    "risk_score": "mean",
    "is_fraud": "mean"
})

customer_risk.sort_values("is_fraud", ascending=False).head()

                    amount  risk_score  is_fraud
customer_id
1066         107103.488889    6.333333  0.155556
1031         108911.586207    6.000000  0.120690
1019         118955.765957    5.808511  0.106383
1030          97885.967742    5.387097  0.096774
1068          99991.520833    5.562500  0.083333

This code creates a "Suspect Watchlist." It shifts the focus from individual transactions to the actual people behind them, identifying which customers are consistently triggering your fraud alerts.
Line-by-Line Explanation
1. df.groupby("customer_id").agg({...})
What it does: It gathers every transaction made by a specific person and calculates their "Profile."
amount: mean: Their average spending habit.
risk_score: mean: Their average "danger level" over time.
is_fraud: mean: The percentage of their total transactions that were flagged as fraud.
Real-Life Example: This is Behavioral Profiling. Instead of judging a customer by one mistake, you are looking at their entire history with your bank.
2. .sort_values("is_fraud", ascending=False).head()
What it does: It puts the most suspicious people at the very top of the list.
Real-Life Example: This is the Top 5 Most Wanted list for your compliance team.

In [640]:
df.set_index("date", inplace=True)

monthly_fraud = df.resample("ME")["is_fraud"].mean()

print(monthly_fraud)

date
2024-01-31    0.034946
2024-02-29    0.044540
2024-03-31    0.038978
2024-04-30    0.036111
2024-05-31    0.038978
2024-06-30    0.051389
2024-07-31    0.045886
Freq: ME, Name: is_fraud, dtype: float64

In [643]:
df["rolling_fraud_rate"] = (
    df["is_fraud"]
    .rolling(100)
    .mean()
)
df

,transaction_id,customer_id,amount,currency,risk_score,is_fraud,amount_band,rolling_fraud_rate
date,,,,,,,,
2024-01-01 00:00:00,1,1051,24408,EUR,2,0,Low,NaN
2024-01-01 01:00:00,2,1092,125116,NGN,8,0,High,NaN
2024-01-01 02:00:00,3,1014,132208,EUR,7,0,High,NaN
2024-01-01 03:00:00,4,1071,18413,EUR,1,0,Low,NaN
2024-01-01 04:00:00,5,1060,114650,USD,5,0,High,NaN
...,...,...,...,...,...,...,...,...
2024-07-27 03:00:00,4996,1048,78475,EUR,6,0,Medium,0.04
2024-07-27 04:00:00,4997,1057,159484,USD,2,0,Very High,0.04
2024-07-27 05:00:00,4998,1038,83212,USD,2,0,Medium,0.04
2024-07-27 06:00:00,4999,1079,76379,NGN,2,0,Medium,0.04
2024-07-27 07:00:00,5000,1096,46591,NGN,3,0,Low,0.04

maybe fraud is treading upwards

In [653]:
df["hour"] = df.index.hour
df["suspicious_flag"] = (
    (df["amount"] > 120000) &
    (df["risk_score"] > 7) &
    (df["hour"].between(0,5))
).astype(int)
df.groupby("suspicious_flag")["is_fraud"].mean()

suspicious_flag
0    0.031494
1    0.380282
Name: is_fraud, dtype: float64